<?php

namespace AppBundle\Repository;

/**
 * AnimePersonnageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimePersonnageRepository extends \Doctrine\ORM\EntityRepository
{
}
