# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_MODO: ROLE_USER
        ROLE_ADMIN: ROLE_MODO

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        # FOS\UserBundle\Model\UserInterface: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      in_memory:
            memory:
                users:
                    admin:
                        password: kitten
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
            pattern: ^/
            anonymous: ~
            http_basic: ~

            # form_login:
                # provider: fos_userbundle
                # csrf_token_generator: security.csrf.token_manager

            logout: true

    access_control:
      # require ROLE_ADMIN for /admin*
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/anime/new, roles: ROLE_MODO }
      - { path: ^/anime/.*/edit, roles: ROLE_MODO }
      - { path: ^/personnage/new, roles: ROLE_MODO }
      - { path: ^/personnage/.*/edit, roles: ROLE_MODO }
